# Site settings
title: "Jerry Resume"
description: "A resume for myself"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Ya Jung Lu"
resume_title:                   "Research Technician · Data Analysist"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "farewell23221@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+886 980-068-628"
#resume_contact_address:         "742 Evergreen Terrace, Springfield"

resume_header_contact_info:     "+886 980-068-628 • farewell23221@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>運用邏輯思維, 統計觀念與程式編寫能力, 有效地解構問題與提出策略.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     False
resume_section_links:           true
resume_section_associations:    False
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://farewellxd.github.io/resume/"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/ya-jung-lu-7261a5100/"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://joelglovier.com"
  resume_medium_url:            "https://medium.com/@farewell23221"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

